version: 0.2

phases:
  install:
    commands:
      - cd frontend/auth-app
      - npm install

  build:
    commands:
      - npm run build  

  post_build:
    commands:
      - echo "Copying build files to S3..."
      - cd frontend/auth-app
      - aws s3 sync build/ s3://prasiddha-bucket-frontend-file-storage --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E11NAE9Z9R46Z3 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/auth-app/build #test
