version: 0.2

phases:
  install:
    commands:
      - cd frontend/auth-app
      - npm install
  build:
    commands:
      - npm run build  
  
  post_build:
    commands:
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id "E11NAE9Z9R46Z3" --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/auth-app/build #test
